name: videna
description: A video decoding and playback library for Flutter.
version: 0.0.1
homepage: https://github.com/Stani-s/videna
repository: https://github.com/Stani-s/videna

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=2.11.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  
  async: ^2.10.0

  image: ^3.1.0

  audio_video_progress_bar: ^1.0.0

  fraction: ^4.1.4

  ffi: ^2.0.1

  path: ^1.8.2

  file_picker: ^5.2.5

dev_dependencies:
  ffigen: ^6.1.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dartdoc: ^6.2.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  #
  # Please refer to README.md for a detailed explanation.
  plugin:
    platforms:
      windows:
        ffiPlugin: true
      linux:
        ffiPlugin: true
